VeterinariaNueva/Controllers/LoginController.cs
using VeterinariaNueva.BaseDatos;
using VeterinariaNueva.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace VeterinariaNueva.Controllers
{

    public class LoginController : Controller
    {
        private readonly VeterinariaDbContext _context;
        private const string _Return_Url = "ReturnUrl";

        public LoginController(VeterinariaDbContext context)
        {
            _context = context;
        }

        [HttpGet]
        public IActionResult Login(string returnUrl)
        {
            // Guardamos la url de retorno para que una vez concluído el login del 
            // usuario lo podamos redirigir a la página en la que se encontraba antes
            TempData[_Return_Url] = returnUrl;
            return View();
        }

        [HttpPost]
        public IActionResult Login(string email, string password, Rol rol)
        {
            string returnUrl = TempData[_Return_Url] as string;

            if (!string.IsNullOrWhiteSpace(email) && !string.IsNullOrWhiteSpace(password))
            {

                var usuario = RNUsuarios.ObtenerUsuario(_context, email, password);

                if (usuario != null)
                {
                    // Se crean las credenciales del usuario que serán incorporadas al contexto
                    ClaimsIdentity identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);

                    // El lo que luego obtendré al acceder a User.Identity.Name
                    identity.AddClaim(new Claim(ClaimTypes.Name, usuario.Email));

                    // Se utilizará para la autorización por roles
                    identity.AddClaim(new Claim(ClaimTypes.Role, usuario.Rol.ToString()));

                    // Lo utilizaremos para acceder al Id del usuario que se encuentra en el sistema.
                    identity.AddClaim(new Claim(ClaimTypes.NameIdentifier, usuario.Id.ToString()));

                    // Lo utilizaremos cuando querramos mostrar el nombre del usuario logueado en el sistema.
                    identity.AddClaim(new Claim(ClaimTypes.GivenName, usuario.Email));

                    //identity.AddClaim(new Claim(nameof(Usuario.Foto), usuario.Foto ?? string.Empty));

                    ClaimsPrincipal principal = new ClaimsPrincipal(identity);

                    // En este paso se hace el login del usuario al sistema
                    HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal).Wait();

                    TempData["LoggedIn"] = true;

                    //if (!string.IsNullOrWhiteSpace(returnUrl))
                    //    return Redirect(returnUrl);

                    if (rol == Rol.Cliente)
                    {
                        return RedirectToAction(nameof(HomeController.Index), "Home");
                    }
                    else
                    {
                        return RedirectToAction(nameof(HomeController.Index), "Home");
                    }


                }
            }
            
            ViewBag.Error = "Usuario o contraseña incorrectos";
            ViewBag.Email = email;
            TempData[_Return_Url] = returnUrl;

            return View();
        }
       
        [Authorize]
        public IActionResult Logout()
        {
            HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme).Wait();

            return RedirectToAction(nameof(HomeController.Index), "Home");
        }

        [Authorize]
        [HttpGet]
        public IActionResult NoAutorizado()
        {
            return View();
        }
    }
}

VeterinariaNueva/Controllers/TurnosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using VeterinariaNueva.BaseDatos;
using VeterinariaNueva.Helper;
using VeterinariaNueva.Models;

namespace VeterinariaNueva.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class TurnosController : Controller
    {
        private readonly VeterinariaDbContext _context;

        public TurnosController(VeterinariaDbContext context)
        {
            _context = context;
        }

        // GET: Turnos
        public async Task<IActionResult> Index()
        {
            return View(await _context.Turnos.ToListAsync());
        }

        // GET: Turnos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var turno = await _context.Turnos
                .FirstOrDefaultAsync(m => m.Id_Turno == id);
            if (turno == null)
            {
                return NotFound();
            }

            return View(turno);
        }

        // GET: Turnos/Create
        [Authorize]
        [AllowAnonymous]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Turnos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

        [Authorize]
        [AllowAnonymous]
        public async Task<IActionResult> Create(Turno turno, int tipo)
        {
            Cliente cliente = RNUsuarios.ObtenerCliente(_context, SessionHelper.GetName(User));
           
            if (cliente == null)
            {
                ViewBag.Error = "¡Necesitas estar logueado para sacar un turno!";
                return View(turno);
            }
            TimeSpan ts = new TimeSpan(turno.Fecha_Hora.Hour, 0, 0);
            turno.Fecha_Hora = turno.Fecha_Hora.Date + ts;          
            turno.Id_Cliente = cliente.Id;
            if (this.ValidarHorario(turno.Fecha_Hora.Hour))
            {
                RNMascotas.AgregarMascota(_context, cliente, turno.Nombre_Mascota, tipo);
                //Si ya existe la mascota para ese cliente, simplemente crea el turno y no la mascota

                if (ModelState.IsValid)
                {
                    if (this.ValidarFecha(turno))
                    {
                    _context.Add(turno);
                    await _context.SaveChangesAsync();               
                    return RedirectToAction(nameof(TurnoExitoso));
                    }
                    else
                    {
                        ViewBag.Error = "¡Esa hora ya está reservada!";
                        return View(turno);
                    }
                }

            }
            else
            {
                ViewBag.Error = string.Format("¡Horario inválido! Nuestro horario es de {0} a {1}.", Turno.HORARIO_APERTURA, Turno.HORARIO_CIERRE);
                return View(turno);
            }             
                
            return View(turno);
        }

        // GET: Turnos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var turno = await _context.Turnos.FindAsync(id);
            if (turno == null)
            {
                return NotFound();
            }
            return View(turno);
        }

        // POST: Turnos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id_Turno,Fecha_Hora,Id_Cliente,Nombre_Mascota")] Turno turno)
        {
            if (id != turno.Id_Turno)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(turno);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TurnoExists(turno.Id_Turno))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(turno);
        }

        // GET: Turnos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var turno = await _context.Turnos
                .FirstOrDefaultAsync(m => m.Id_Turno == id);
            if (turno == null)
            {
                return NotFound();
            }

            return View(turno);
        }

        // POST: Turnos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var turno = await _context.Turnos.FindAsync(id);
            _context.Turnos.Remove(turno);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TurnoExists(int id)
        {
            return _context.Turnos.Any(e => e.Id_Turno == id);
        }

        private bool ValidarFecha(Turno turno)
        {
            List<Turno> listaTurnos = _context.Turnos.ToList();

            var noExistia = !listaTurnos.Any(t => t.Fecha_Hora == turno.Fecha_Hora);

            return noExistia;
        }

        private bool ValidarHorario(int hora)
        {
            bool esValido = false;

            if (hora >= Turno.HORARIO_APERTURA && hora <= Turno.HORARIO_CIERRE)
                esValido = true;

            return esValido;

        }

        public ActionResult HistorialClientes(int id)
        {  
            var lista = new ViewModel.VMHistorialList();                    
            List<Turno> turnos = _context.Turnos.Where(o => o.Id_Cliente == id).ToList();
            lista.Historial = new List<ViewModel.VMHistorial>();
            var cliente = RNUsuarios.ObtenerCliente(_context, turnos.ElementAt(0).Id_Cliente);
            ViewBag.Cliente = cliente.Email;
           
            foreach (var turno in turnos)
            {
                ViewModel.VMHistorial modelo = new ViewModel.VMHistorial();

                var mascota = RNMascotas.ObtenerMascota(_context, turno.Nombre_Mascota);

                if (mascota != null)
                {
                    modelo.Cliente = cliente;
                    modelo.Mascota = mascota;
                    modelo.Turno = turno.Fecha_Hora;

                    lista.Historial.Add(modelo);
                }
             
            }

             return View(lista);
        }
        

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult HistorialClientes(ViewModel.VMHistorialList lista)
        {

            return RedirectToAction(nameof(HistorialClientes));
        }

        public ActionResult HistorialMascotas(int id, string nombreMascota)
        {
            var lista = new ViewModel.VMHistorialList();
            List<Turno> turnos = _context.Turnos.Where(o => o.Id_Cliente == id && nombreMascota == o.Nombre_Mascota).ToList();
            lista.Historial = new List<ViewModel.VMHistorial>();
            var mascota = RNMascotas.ObtenerMascota(_context, turnos.ElementAt(0).Id_Cliente, nombreMascota);
            var cliente = RNUsuarios.ObtenerCliente(_context, turnos.ElementAt(0).Id_Cliente);

            if (mascota == null || cliente == null)
            {
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Mascota = mascota.Nombre;
            foreach (var turno in turnos)
            {
                ViewModel.VMHistorial modelo = new ViewModel.VMHistorial();

                modelo.Cliente = cliente;
                modelo.Mascota = mascota;
                modelo.Turno = turno.Fecha_Hora;

                lista.Historial.Add(modelo);
            }

            return View(lista);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult HistorialMascotas(ViewModel.VMHistorialList lista)
        {

            return RedirectToAction(nameof(HistorialMascotas));
        }

        [Authorize]
        [AllowAnonymous]
        public IActionResult TurnoExitoso ()
        {
            return View();
        }

    }

}

VeterinariaNueva/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VeterinariaNueva</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

@using VeterinariaNueva.Helper

<body>
    <header>
        <div class="container">
            <div id="branding">
                <h1>
                    Veterinaria<span class="highlight"> ORT</span>
                </h1>
            </div>
            <nav>
                <ul>
                    <li>
                        <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Turnos" asp-action="Create">Turnos</a>
                    </li>
                    <li>
                        @if (SessionHelper.GetRole(User).Equals("Administrador"))
                        {
                        <a asp-area="" asp-controller="Clientes" asp-action="Create">Clientes</a>
                        }
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Home" asp-action="Acerca">Acerca de</a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Home" asp-action="Precios">Precios</a>
                    </li>
                    <li>
                        @if (SessionHelper.GetName(User).Equals(""))
                        {
                            <a asp-area="" asp-controller="Login" asp-action="Login">Login</a>
                        }

                        else
                        {
                            <a asp-area="" asp-controller="Login" asp-action="Logout">Logout</a>
                        }
                    </li>
                    <li>
                        @if (!SessionHelper.GetName(User).Equals(""))
                         {
                            <p> ¡Bienvenido/a @SessionHelper.GetName(User)! </p>
                         }

                    </li>
                        
                </ul>
            </nav>
        </div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <section id="newsletter">
        <div class="container">
            <h1>¡Suscribite para enterarte de todo lo nuevo!</h1>
            <form>
              <a class="my-5 btn btn-outline-primary btn-lg" asp-area="" asp-controller="Home" asp-action="Suscripcion">Suscribirse</a>
            </form>
        </div>
    </section>
    <footer>
        <p>Veterinaria ORT web design &Copy; 2021 </p>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

VeterinariaNueva/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Veterinaria</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body class="fondo">
    
    <header>
      
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
    
</body>
</html>